use crate::wrangler::WranglerBindings;
use serde::{Deserialize, Serialize};

pub const START_MARKER: &str = "// BEGIN FLAREOPS MANAGED BINDINGS";
pub const END_MARKER: &str = "// END FLAREOPS MANAGED BINDINGS";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum SyncMode {
    #[default]
    Astro,
    Worker,
    Standalone,
}

impl std::str::FromStr for SyncMode {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "astro" => Ok(SyncMode::Astro),
            "worker" | "workers" => Ok(SyncMode::Worker),
            "standalone" => Ok(SyncMode::Standalone),
            _ => Err(format!(
                "Unknown sync mode '{s}'. Valid: astro, worker, standalone"
            )),
        }
    }
}

#[derive(Debug, Clone)]
pub struct GeneratorOptions {
    pub mode: SyncMode,
    pub include_comments: bool,
}

impl Default for GeneratorOptions {
    fn default() -> Self {
        Self {
            mode: SyncMode::Astro,
            include_comments: true,
        }
    }
}

pub fn generate_managed_block(bindings: &WranglerBindings, options: &GeneratorOptions) -> String {
    let mut out = String::new();
    out.push_str(START_MARKER);
    out.push('\n');
    out.push_str("/// <reference types=\"@cloudflare/workers-types\" />\n\n");

    let required_types = bindings.required_workers_types();
    if !required_types.is_empty() {
        out.push_str(&format!(
            "import type {{ {} }} from \"@cloudflare/workers-types\";\n\n",
            required_types.join(", ")
        ));
    }

    out.push_str("export interface CloudflareEnv {\n");
    if bindings.is_empty() {
        out.push_str("\t// No bindings defined in wrangler configuration\n");
    } else {
        for b in &bindings.bindings {
            if options.include_comments
                && let Some(ref comment) = b.comment
            {
                out.push_str(&format!("\t/** {comment} */\n"));
            }
            out.push_str(&format!("\t{}: {};\n", b.name, b.ts_type()));
        }
    }
    out.push_str("}\n");
    out.push_str(END_MARKER);
    out
}

pub fn generate_complete_env_dts(
    bindings: &WranglerBindings,
    options: &GeneratorOptions,
    custom_locals: Option<&str>,
) -> String {
    let mut out = String::new();
    out.push_str("/* eslint-disable */\n");
    out.push_str("/* prettier-ignore */\n");
    out.push_str("// Generated by flareops. DO NOT EDIT DIRECTLY inside the managed block.\n\n");

    let managed_block = generate_managed_block(bindings, options);
    out.push_str(&managed_block);
    out.push_str("\n\n");

    match options.mode {
        SyncMode::Astro => {
            out.push_str("declare namespace App {\n");
            out.push_str("\tinterface Locals extends CloudflareEnv {\n");
            if let Some(custom) = custom_locals {
                let trimmed = custom.trim();
                if !trimmed.is_empty() {
                    for line in trimmed.lines() {
                        out.push_str(&format!("\t\t{line}\n"));
                    }
                }
            }
            out.push_str("\t}\n");
            out.push_str("}\n\n");
            out.push_str("export type Env = CloudflareEnv;\n");
            out.push_str(
                "export type Runtime = import(\"@astrojs/cloudflare\").Runtime<CloudflareEnv>;\n",
            );
        }
        SyncMode::Worker => {
            out.push_str("export type Env = CloudflareEnv;\n\n");
            out.push_str("declare global {\n");
            out.push_str("\t// Global Worker environment\n");
            out.push_str("\ttype Env = CloudflareEnv;\n");
            out.push_str("}\n");
        }
        SyncMode::Standalone => {
            out.push_str("export type Env = CloudflareEnv;\n");
        }
    }

    out
}
